--- makefile for lua-5.3
--
if not WINDOWS then quit("We are not running on Windows?") end;
--
-----------------------------------------------------------------------------------------------
--
LUAROOT     = LUAROOT or PWD.."/.."
LUA_BIN     = LUA_BIN or LUAROOT.."/_install"               -- install dir
TEMPDIR     = TEMPDIR or LUAROOT.."/tmp"                    -- dir for intermediate files

local LUA_VERSION = "53"
local LUA_IDIR    = LUA_BIN.."/include/"..LUA_VERSION -- dir for headers and static libs
local LUA_CDIR    = LUA_BIN.."/lib/"..LUA_VERSION     -- dir for c modules
local LUA_LDIR    = LUA_BIN.."/lua"                   -- dir for lua modules 
local LUA_ETC_DIR = LUA_BIN.."/etc"                   -- dir for documentation, tests, etc.

local lua_core = "\z
  lapi lcode lctype ldebug ldo ldump lfunc lgc llex lmem lobject \z
  lopcodes lparser lstate lstring ltable ltm lundump lvm lzio \z
  lauxlib lbaselib lbitlib lcorolib ldblib liolib \z
  lmathlib loslib lstrlib ltablib lutf8lib loadlib linit"

local LUAICON = wresource {"lua53", src="icon", base="src", odir=TEMPDIR} -- icon resources
local LUAICN2 = wresource {"luac53",src="icon", base="src", odir=TEMPDIR} -- icon resources
local LUA_C   = c99 {"lua53", src="lua", base="src", odir=TEMPDIR, from="lua53:defines"}       -- lua program c source
local LUAC_C  = c99 {"lua53", src="luac", base="src", odir=TEMPDIR, from="lua53s:defines"}     -- luac program c source
local LIB_C   = c99 {"lua53_s", src=lua_core, base="src", odir=TEMPDIR, from="lua53s:defines"} -- static lib c source
local DLL_C   = c99 {"lua53_d", src=lua_core, base="src", odir=TEMPDIR, from="lua53:defines"}  -- dynamic lib c source
--
local LUALIB  = c99.library {'lua53', odir=LUA_IDIR, inputs=LIB_C}                     -- static lua runtime lib
local LUADLL  = c99.shared  {'lua53', odir=LUA_BIN, inputs=DLL_C}                      -- dynamic lua runtime lib
local LUAEXE  = c99.program {'lua53', odir=LUA_BIN, inputs={LUA_C, LUAICON, LUADLL}}   -- lua executable
local LUAC    = c99.program {'luac53', odir=LUA_BIN, inputs={LUAC_C, LUAICN2, LUALIB}} -- luac executable
--
local LUAINC  = file {src="lua.h lua.hpp luaconf.h lualib.h lauxlib.h", base="src", odir=LUA_IDIR}
local LUADOC  = file {src="*", base="doc", odir=LUA_ETC_DIR.."/lua53/doc"}
local LUAETC  = file {src="*.ico", base="etc", odir=LUA_IDIR}
--
local LUA = group {LUAEXE, LUAC, LUAINC, LUADOC, LUAETC}

target("lua53", LUA)

default(LUA)
--
define_need{'lua53',  -- lua53, dynamically linked libs
  libs          = "lua53", 
  incdir        = LUA_IDIR, 
  defines       = "LUA_BUILD_AS_DLL LUA_COMPAT_MODULE", 
  libdir        = LUA_BIN .. " " .. LUA_IDIR,
  prerequisites = "lua53"
};

define_need{'lua53s', -- lua53, statically linked libs
  libs          = "lua53",
  incdir        = LUA_IDIR, 
  defines       = "LUA_COMPAT_MODULE", 
  libdir        = LUA_IDIR,
  prerequisites = "lua53"
};
--
-- aliases for compiling the modules
make.Needs "lua=lua53"   
make.Needs "luas=lua53s" 

