--- makefile for lua-5.2, lua-5.3 and modules, ...
-- Build a lua environment for windows, where all lua versions resides side by side in one 
-- directory tree including there modules, libraries, documentation and lua tools.
-- It creates a "_install" folder containing all content you may want for copy 
-- to "c:\lua" (for instance).
-- This makefile is not intended to work on other OS than Windows.
-- it is tested with TDM-GCC-64 (https://tdm-gcc.tdragon.net/)
--
if not WINDOWS then quit("We are not running on Windows?") end;
--
make.toolchain "gnu32"; -- compile to 32bit executables. (or use -m32 commandline parameter)
--make.toolchain "gnu64"; -- compile to 64bit executables. (or use -m64 commandline parameter)
--make.toolchain "msc";
--make.set_flags {OPTIMIZE="Os", STRICT=true, PREFIX="x86_64-w64-mingw32"};
-----------------------------------------------------------------------------------------------
--
LUAROOT = PWD                  -- base of the lua build tree
LUA_BIN = LUAROOT.."/_install" -- install dir
          .. (M32 and "32" or "") 
          .. (M64 and "64" or "") 
TEMPDIR = LUAROOT.."/tmp"      -- dir for intermediate files
          .. (M32 and "/32" or "") 
          .. (M64 and "/64" or "") 

CFLAGS  = "-Werror" -- Make all warnings into errors.
--
-----------------------------------------------------------------------------------------------
--
make "lua51"
make "modules"
make "lua52"
make "modules"
make "lua53"
make "modules"
--make "tools"

--[[-- This build script a patched package.path and package.cpath:

for lua-5.3:

 #define LUA_LDIR	"!\\lua\\"
 #define LUA_CDIR	"!\\lib\\53\\"
 #define LUA_PATH_DEFAULT  \
 		LUA_LDIR"?.lua;"  LUA_LDIR"?\\init.lua;" \
		LUA_CDIR"?.lua;"  LUA_CDIR"?\\init.lua;" ".\\?.lua"
 #define LUA_CPATH_DEFAULT \
		LUA_CDIR"?53.dll;"	LUA_CDIR"?.dll;" \
		"!\\?53.dll;"	"!\\?.dll"

--]]--